GET http://localhost:3333/users

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Fleipe lucas",
    "emails": "dlsf@gmail.com",
    "age": 12
}

###

PUT http://localhost:3333/users/
Content-Type: application/json

{
    "name": "Fleipe lucas",
    "emails": "dlsf@gmail.com",
    "age": 12
}