POST http://localhost:3001/videos
Content-Type: application/json

{
    "title": "Novo video",
    "description": "Esse e meu primeiro video",
    "duration": 180
}

###

GET http://localhost:3001/videos

###

PUT http://localhost:3001/videos/1c2695a7-4abb-46ba-a5cb-7c9c5884103d
Content-Type: application/json

{
    "title": "Editado",
    "description": "Esse e meu primeiro video",
    "duration": 180
}

###
DELETE http://localhost:3001/videos/ce12f2df-e953-400e-b109-66950ad40e8d