GET http://localhost:3333/users?name=Aryla Mayane Gomes Chagas 

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Arila Mayane",
    "email": "ilovaarila@gmail.com",
    "age": 16
}

###

PUT http://localhost:3333/users/22
Content-Type: application/json

{
    "name": "Aryla Mayane Gomes Chagas",
    "email": "ilovewarilasomuch@gmail.com",
    "age": 18
}

###

DELETE http://localhost:3333/users/20
